# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a792c9357967ecaad17f7b72739573e58fcf583aa9754995d1abad0a261fa21a209a5abf174d55e905321f16397b6261081d067ec0e2716d42df34a6c53d688

test:
  secret_key_base: adb6c97f881a3e9f344069267e76f66d2ab2ec63a4e85a9495aad39198e1c324d8f8d7cd1ca751af89e551cccbe63532b244ca2f870d17683a1c6daf39a37060

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
